# Generated by Django 4.2.9 on 2024-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubank_auth_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='certificate',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
