# Generated by Django 4.2.9 on 2024-09-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubank_auth_server', '0002_client_certificate_client_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='client',
            name='verified',
        ),
    ]
